Repository gaidds/Django-crm-project, pull requests merged in 2024-08, with the labels that each got.

#3 I1 bcip 20 create google login put endpoint
  common/admin.py
  common/migrations/0010_alter_attachments_created_by_authconfig.py
  common/migrations/0011_remove_authconfig_organization.py
  common/models.py
  common/serializer.py
  common/urls.py
  common/views.py
Labels: under test and review

#5 Fix google login config
  common/serializer.py
  common/urls.py
  common/views.py
Labels: ready to merge

#7 I1BCIP-8 create toggle google login config
  common/admin.py
  common/migrations/0010_alter_attachments_created_by_authconfig.py
  common/migrations/0011_remove_authconfig_organization.py
  common/models.py
  common/serializer.py
  common/urls.py
  common/views.py
Labels: ready to merge

#12 Create change password
  common/migrations/0012_merge_20240810_2346.py
  common/serializer.py
  common/urls.py
  common/views.py
Labels: under test and review

#11 I1 bcip 6 create user profile crud
  common/migrations/0012_merge_20240810_2346.py
  common/serializer.py
  common/urls.py
  common/views.py
Labels: not ready

#22 Permissions contacts
  contacts/views.py
Labels: ready to merge

#24 Fix accounts permissions
  accounts/views.py
  common/migrations/0014_alter_profile_role.py
  common/views.py
Labels: ready to merge

#25 Permissions leads
  leads/views.py
Labels: under test and review

#21 Permissions opportunities
  opportunity/serializer.py
  opportunity/views.py
Labels: under test and review

#17 I1-BCIP-10 create disable new account creation
  common/views.py
Labels: under test and review

#15 added put auth-config
  common/migrations/0014_create_default_authconfig.py
  common/views.py
Labels: ready to merge

#28 I1BCIP-28 create forgot password option
  common/serializer.py
  common/tasks.py
  common/templates/forgot_password_email.html
  common/urls.py
  common/views.py
Labels: under test and review
