Repository gaidds/Django-crm-project, pull requests merged in 2024-10, with the labels that each got.

#36 Fix Context For Modals
  accounts/serializer.py
  accounts/views.py
  common/serializer.py
  common/views.py
  contacts/views.py
Labels: Needed to test frontend

#38 I1BCIP-124-CURRENCY-UPDATE
  accounts/views.py
  common/utils.py
  common/views.py
  crm/settings.py
Labels: under test and review, ready to merge

#40 Create closed deals per month
  common/views.py
  deals/migrations/0002_deal_real_close_date.py
  deals/models.py
  deals/views.py
Labels: ready to merge

#39 I1BCIP-123-create-service-converts-deals
  common/views.py
Labels: ready to merge

#42 Profile pic has been added to contacts.
  contacts/migrations/0006_contact_profile_pic.py
  contacts/models.py
  contacts/serializer.py
  contacts/swagger_params1.py
  contacts/views.py
Labels: ready to merge

#41 I1BCIP-66 fix org
  common/serializer.py
Labels: ready to merge

#43 I1BCIP32-Fix-Bug-Created/Updated_by
  common/base.py
  common/views.py
Labels: under test and review

#48 all stages count
  common/views.py
Labels: under test and review, ready to merge

#46 I1BCIP-128 -track-percentage-change
  common/views.py
Labels: under test and review

#44 I1BCIP-129 create group deals by source
  common/views.py
Labels: under test and review

#49 Calculating win ratio per toal closed deals
  common/views.py
Labels: under test and review, ready to merge

#45 I1BCIP-126-monthly-closed-deals-trendline
  common/utils.py
  common/views.py
  deals/models.py
Labels: under test and review
